Vendure worker deply workflow (#67)
* - created new github action for vendure worker;

* - rename worker to be-vendure_worker for avoiding confusions;

* - update .env.production instead of overwriting it;

* - fixed worker build on github workflow.

diff --git a/.github/workflows/deploy-be-vendure-worker.yml b/.github/workflows/deploy-be-vendure-worker.yml
--- a/.github/workflows/deploy-be-vendure-worker.yml
+++ b/.github/workflows/deploy-be-vendure-worker.yml
@@ -128,18 +128,21 @@ jobs:
       - name: Install dependencies
         run: npm ci --legacy-peer-deps
 
-      - name: Build be-vendure application
+      - name: Build be-vendure worker
         env:
           NX_PREFER_TS_NODE: true
         run: |
-          echo ">>> Running NX build for be-vendure…"
-          npx nx run be-vendure:build:production
+          echo ">>> Running NX build for be-vendure worker…"
+          npx nx run be-vendure:build-worker:production
 
           echo ">>> Listing all dist/apps directories:"
           ls -R dist/apps
 
           echo ">>> Contents of the be-vendure build folder:"
           ls -l dist/apps/backends/be-vendure || echo "Folder not found: dist/apps/backends/be-vendure"
+          
+          echo ">>> Checking for main-worker.js:"
+          ls -l dist/apps/backends/be-vendure/main-worker.js || echo "main-worker.js not found!"
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
